# Miscelaneous
favicon: /favicon.ico

# fancybox gallery
fancybox: true

# main menu navigation
# ====================================
menu:
  HOME: /
  ARCHIVES: /archives
  #category: /categories
  #tags: /tags
  ABOUT: /about

# site logo introduce and footer quote
# ====================================
logo: Chuie
introduce: "Do you like rain"
quote: "关于人生我何必开窍"

# social club
# ====================================
social:
  weibo: https://weibo.com
  github: https://github.com/
  douban: https://www.douban.com/
  steam:
  linkedin:
  facebook:
  twitter:
  tumblr:
  instagram:
  stackoverflow:
  rss:

# third party services settings
# ===================================

#leanCloud
leancloud:
  app_id:
  app_key:

# comments
# Valine comment system. https://valine.js.org
valine:
  comment_name: 留言板 #your comment area title
  enable: true # if you want use valine, please set this value to true
  app_id:  # your leancloud appId
  app_key:  # your leancloud appKey
  notify: false # Mail notify
  verify: false # Verify code
  avatar: retro # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: 欢迎留言~ O(∩_∩)O # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size

#disqus
disqus_shortname:


# ==================================
version: 1.0
# ==================================
